export const handleError = async (error: any) => {
  console.log("this is error object", error);
  return error;
};
